import { LAYER, DependencyResolver } from './ContinuousEffectEngine.js';

// Phase 61: explicit CR 613 ordering helpers for effects generated by cards.
export class LayerInteractionService {
  constructor(engine) { this.engine = engine; this.dependencies = new DependencyResolver(); }
  ordered(effects = []) { return this.dependencies.order(effects); }
  dependencyGraph(effects = []) {
    const ids = new Set(effects.map(e => e.id));
    return new Map(effects.map(e => [e.id, (e.dependsOn || []).filter(id => ids.has(id))]));
  }
  registerTypeChange(sourceId, filter, transform, options = {}) {
    return this.engine.continuous.register({ sourceId, filter, transform, layer: LAYER.TYPE, ...options });
  }
  registerAbilityChange(sourceId, filter, transform, options = {}) {
    return this.engine.continuous.register({ sourceId, filter, transform, layer: LAYER.ABILITY, ...options });
  }
  registerPTSet(sourceId, filter, transform, options = {}) {
    return this.engine.continuous.register({ sourceId, filter, transform, layer: LAYER.PT_SET, ...options });
  }
  registerPTModify(sourceId, filter, transform, options = {}) {
    return this.engine.continuous.register({ sourceId, filter, transform, layer: LAYER.PT_MODIFY, ...options });
  }
}
