import test from 'node:test'; import assert from 'node:assert/strict';
import { KeywordRuntimeService } from '../src/engine/KeywordRuntimeService.js';
const card=(id,extra={})=>({instanceId:id,cardId:id,controller:'player',owner:'player',zone:'battlefield',counters:{},modifiers:{power:0,toughness:0,keywords:[]},...extra});
function harness(defs={}){const a=card('a'),b=card('b');const state={turn:1,activePlayer:'player',players:{player:{life:40,battlefield:[a,b],hand:[],library:[card('draw',{zone:'library'})],manaPool:{W:10,U:10,B:10,R:10,G:10,C:10}},ai:{life:40,battlefield:[],hand:[],library:[],manaPool:{}}},combat:{attackDefendingPlayers:{}},turnMemory:{player:{},ai:{}}};const e={state,db:defs,playerIds:()=>['player','ai'],opponents:()=>['ai'],findPermanent:id=>[...state.players.player.battlefield,...state.players.ai.battlefield].find(x=>x.instanceId===id),static:{isType:()=>true},counters:{add:(x,k,n)=>x.counters[k]=Number(x.counters[k]||0)+n},sacrificePermanent:x=>{state.players[x.controller].battlefield=state.players[x.controller].battlefield.filter(y=>y!==x);x.zone='graveyard'},changeLife:(p,n)=>state.players[p].life+=n,drawCard:(p,n)=>{for(let i=0;i<n;i++){const x=state.players[p].library.shift();if(x)state.players[p].hand.push(x)}},mana:{canAfford:()=>true,pay:()=>true}};e.keywordRuntime=new KeywordRuntimeService(e);return {e,a,b};}
test('100 Soulbond pairs and unpairs when control relationship breaks',()=>{const {e,a,b}=harness({a:{soulbond:true}});assert.equal(e.keywordRuntime.soulbond(a,b.instanceId).paired,true);b.controller='ai';e.keywordRuntime.validatePairs();assert.equal(a.soulbondPartnerId,null);});
test('101 Exploit sacrifices a legal creature and marks source exploited',()=>{const {e,a,b}=harness();e.keywordRuntime.exploit(a,b.instanceId);assert.equal(a.exploited,true);assert.equal(b.zone,'graveyard');});
test('102 Cumulative upkeep adds age counters and sacrifices when unpaid',()=>{const {e,a}=harness({a:{cumulativeUpkeep:{mana:'{1}'}}});e.keywordRuntime.cumulativeUpkeep(a,{pay:false});assert.equal(a.counters.age,1);assert.equal(a.zone,'graveyard');});
test('103 Extort drains each opponent and gains aggregate life',()=>{const {e,a}=harness();e.keywordRuntime.extort(a,{pay:true});assert.equal(e.state.players.ai.life,39);assert.equal(e.state.players.player.life,41);});
test('104 Unleash counter choice is represented authoritatively',()=>{const {e,a}=harness();e.keywordRuntime.unleash(a,true);assert.equal(a.counters['+1/+1'],1);assert.equal(a.unleashed,true);});
test('105 Riot supports counter and haste choices',()=>{const {e,a,b}=harness();e.keywordRuntime.riot(a,'counter');e.keywordRuntime.riot(b,'haste');assert.equal(a.counters['+1/+1'],1);assert.ok(b.modifiers.keywords.includes('haste'));});
test('106 Melee scales by distinct defending opponents and cleans up',()=>{const {e,a}=harness();e.state.combat.attackDefendingPlayers={a:'ai'};assert.equal(e.keywordRuntime.melee(a),1);assert.equal(a.modifiers.power,1);e.keywordRuntime.cleanup();assert.equal(a.modifiers.power,0);});
test('107 Bloodthirst enters with counters only after opponent damage',()=>{const {e,a}=harness({a:{bloodthirst:2}});e.state.turnMemory.player.opponentDamagedThisTurn=true;assert.equal(e.keywordRuntime.bloodthirst(a),2);assert.equal(a.counters['+1/+1'],2);});
test('108 Ravenous applies X counters and threshold draw',()=>{const {e,a}=harness({a:{ravenous:true}});e.keywordRuntime.ravenous(a,5);assert.equal(a.counters['+1/+1'],5);assert.equal(e.state.players.player.hand.length,1);});
test('109 Jump-start remains encoded as graveyard cast + discard + exile rule',()=>{const d={castingOptions:[{id:'jump-start',fromZone:'graveyard',castOption:'jump-start',additionalCosts:[{type:'discard',count:1}],exileOnLeaveStack:true}]};assert.equal(d.castingOptions[0].exileOnLeaveStack,true);assert.equal(d.castingOptions[0].additionalCosts[0].type,'discard');});
test('110 runtime service is fail-closed on illegal soulbond/exploit choices',()=>{const {e,a}=harness();assert.throws(()=>e.keywordRuntime.soulbond(a,'missing'));assert.throws(()=>e.keywordRuntime.exploit(a,'missing'));});
