import test from 'node:test';import assert from 'node:assert/strict';import {KeywordRuntimeService} from '../src/engine/KeywordRuntimeService.js';
const C=(id,x={})=>({instanceId:id,cardId:id,controller:'p',owner:'p',zone:'battlefield',power:2,toughness:2,counters:{},modifiers:{power:0,toughness:0,keywords:[]},...x});
function H(defs={}){const a=C('a'),b=C('b');const state={turn:1,players:{p:{life:40,battlefield:[a,b],graveyard:[],hand:[]},q:{life:40,battlefield:[C('q1',{controller:'q',owner:'q'})],graveyard:[],hand:[]}}};const e={state,db:defs,playerIds:()=>['p','q'],opponents:id=>id==='p'?['q']:['p'],static:{isType:(c,t)=>new RegExp(t,'i').test(defs[c.cardId]?.typeLine||c.typeLine||'Creature'),derivedStats:c=>({power:c.power+(c.modifiers?.power||0)})},counters:{add:(c,k,n)=>c.counters[k]=Number(c.counters[k]||0)+n},findPermanent:id=>Object.values(state.players).flatMap(p=>p.battlefield).find(c=>c.instanceId===id),sacrificePermanent:c=>{const p=state.players[c.controller];p.battlefield=p.battlefield.filter(x=>x!==c);p.graveyard.push(c);c.zone='graveyard'},changeLife:(id,n)=>state.players[id].life+=n,effects:{createToken:(id,d,n)=>{for(let i=0;i<n;i++)state.players[id].battlefield.push(C(`t${i}`,{cardId:d.name,token:true,typeLine:d.typeLine,power:d.power,toughness:d.toughness}))}}};e.keywordRuntime=new KeywordRuntimeService(e);return{e,a,b};}
test('221 saddle',()=>{const{e,a,b}=H({a:{saddle:1}});assert.equal(e.keywordRuntime.saddle(a,['b']),2);assert.ok(a.saddled&&b.tapped);e.keywordRuntime.cleanup();assert.equal(a.saddled,false)});
test('222 ward life',()=>{const{e,a}=H({a:{wardCost:{amount:2}}});assert.equal(e.keywordRuntime.wardLife(a,'p'),true);assert.equal(e.state.players.p.life,38)});
test('223 fading',()=>{const{e,a}=H({a:{fading:1}});e.keywordRuntime.fading(a,true);assert.equal(e.keywordRuntime.fading(a),true);assert.equal(e.keywordRuntime.fading(a),false);assert.equal(a.zone,'graveyard')});
test('224 rampage',()=>{const{e,a}=H({a:{rampage:2}});assert.equal(e.keywordRuntime.rampage(a,3),4);assert.equal(a.modifiers.power,4);e.keywordRuntime.cleanup();assert.equal(a.modifiers.power,0)});
test('225 afterlife',()=>{const{e,a}=H({a:{afterlife:2}});assert.equal(e.keywordRuntime.afterlife(a),2);assert.equal(e.state.players.p.battlefield.length,4)});
test('226 annihilator',()=>{const{e,a}=H({a:{annihilator:1}});assert.equal(e.keywordRuntime.annihilator(a,'q',['q1']),1);assert.equal(e.state.players.q.battlefield.length,0)});
test('227 reconfigure',()=>{const{e,a,b}=H();assert.equal(e.keywordRuntime.reconfigure(a,'b'),'b');assert.equal(a.attachedTo,'b');e.keywordRuntime.reconfigure(a);assert.equal(a.attachedTo,undefined)});
test('228 amass',()=>{const{e,a}=H();const army=e.keywordRuntime.amass(a,'Orc',2);assert.equal(army.counters['+1/+1'],2)});
test('230 collect evidence',()=>{const{e,a}=H({g:{typeLine:'Creature',manaValue:6}});const g=C('g',{zone:'graveyard'});e.state.players.p.graveyard=[g];assert.equal(e.keywordRuntime.collectEvidence(a,['g'],6),6);assert.equal(g.zone,'exile')});
test('231 tribute',()=>{const{e,a}=H({a:{tribute:3}});assert.equal(e.keywordRuntime.tribute(a,true),true);assert.equal(a.counters['+1/+1'],3)});
test('236 soulshift',()=>{const{e,a}=H({a:{soulshift:5},s:{typeLine:'Creature — Spirit',manaValue:4}});const s=C('s',{zone:'graveyard'});e.state.players.p.graveyard=[s];e.keywordRuntime.soulshift(a,'s');assert.equal(s.zone,'hand')});
test('237 venture',()=>{const{e}=H();assert.equal(e.keywordRuntime.venture('p','Lost Mine').room,'Lost Mine')});
