import test from 'node:test'; import assert from 'node:assert/strict';
import { applyTargetedDeckDamageImplementations } from '../src/cards/index.js'; import { GameEngine } from '../src/engine/GameEngine.js';
const raw={commander:{id:'commander',name:'Commander',typeLine:'Legendary Creature',manaCost:'{B}{R}',colors:['B','R'],power:2,toughness:2,abilities:[]},ign:{id:'ign',name:"Chandra's Ignition",typeLine:'Sorcery',manaCost:'{3}{R}{R}',colors:['R']},back:{id:'back',name:'Backlash',typeLine:'Instant',manaCost:'{1}{B}{R}',colors:['B','R']},del:{id:'del',name:'Delirium',typeLine:'Instant',manaCost:'{1}{B}{R}',colors:['B','R']},pop:{id:'pop',name:'Price of Progress',typeLine:'Instant',manaCost:'{1}{R}',colors:['R']},big:{id:'big',name:'Big',typeLine:'Creature',manaCost:'{3}{R}',colors:['R'],power:5,toughness:5,abilities:[]},small:{id:'small',name:'Small',typeLine:'Creature',manaCost:'{1}',colors:[],power:2,toughness:2,abilities:[]},basic:{id:'basic',name:'Swamp',typeLine:'Basic Land — Swamp',abilities:[]},nonbasic:{id:'nonbasic',name:'Tower',typeLine:'Land',abilities:[]}};
const db=applyTargetedDeckDamageImplementations(raw), deck={id:'d',name:'d',commander:'commander',cards:[{id:'commander',quantity:1}]}; function eng(){return new GameEngine(deck,{...deck,id:'o'},db,{validateDecks:false,rng:()=>.5});} let n=0; function put(e,p,id){let c={instanceId:`${id}-${++n}`,cardId:id,owner:p,controller:p,zone:'battlefield',tapped:false,phasedOut:false,summoningSick:false,counters:{},damageMarked:0,modifiers:{power:0,toughness:0,keywords:[]}};e.state.players[p].battlefield.push(c);return c;}
test('damage tranche certified',()=>{for(const x of ['ign','back','del','pop'])assert.equal(db[x].certificationEligible,true)});
test("Chandra's Ignition uses chosen creature power and damages opponents and other creatures",()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],a=put(e,p,'big'),b=put(e,o,'small'),life=e.state.players[o].life;e.effects.resolve(db.ign.spellEffects[0],{controller:p,source:{cardId:'ign'},targets:[a.instanceId],targeted:true});assert.equal(e.state.players[o].life,life-5);assert.equal(e.findPermanent(b.instanceId),null);assert.ok(e.findPermanent(a.instanceId));});
test('Backlash taps untapped creature and it damages its controller equal to power',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],a=put(e,o,'big'),life=e.state.players[o].life;e.effects.resolve(db.back.spellEffects[0],{controller:p,targets:[a.instanceId],targeted:true});assert.equal(a.tapped,true);assert.equal(e.state.players[o].life,life-5);});
test('Delirium taps opposing creature, damages controller, and marks next untap skipped',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],a=put(e,o,'big'),life=e.state.players[o].life;e.effects.resolve(db.del.spellEffects[0],{controller:p,targets:[a.instanceId],targeted:true});assert.equal(a.tapped,true);assert.equal(a.skipNextUntap,true);assert.equal(e.state.players[o].life,life-5);});
test('Price of Progress deals 2 per nonbasic land to each player',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'basic');put(e,p,'nonbasic');put(e,o,'nonbasic');put(e,o,'nonbasic');let lp=e.state.players[p].life,lo=e.state.players[o].life;e.effects.resolve(db.pop.spellEffects[0],{controller:p,source:{cardId:'pop'}});assert.equal(e.state.players[p].life,lp-2);assert.equal(e.state.players[o].life,lo-4);});
