import test from 'node:test';import assert from 'node:assert/strict';import {applyTargetedDeckSpecialImplementations} from '../src/cards/index.js';import {GameEngine} from '../src/engine/GameEngine.js';
const names=['Deadly Rollick','Pyroblast','Forsaken Wastes','Glistening Oil','Thief of Blood'];
const raw={cmd:{id:'cmd',name:'Commander',typeLine:'Legendary Creature',manaCost:'{B}{R}',colors:['B','R'],power:2,toughness:2,abilities:[]},blue:{id:'blue',name:'Blue Bear',typeLine:'Creature',manaCost:'{1}{U}',colors:['U'],power:2,toughness:2,abilities:[]},red:{id:'red',name:'Red Bear',typeLine:'Creature',manaCost:'{1}{R}',colors:['R'],power:2,toughness:2,abilities:[]}};names.forEach((x,i)=>raw['s'+i]={id:'s'+i,name:x,typeLine:i===2?'Enchantment':i===3?'Enchantment — Aura':i===4?'Creature — Vampire':'Instant',manaCost:i===0?'{3}{B}':i===1?'{R}':'{2}{B}',colors:i===1?['R']:['B'],power:i===4?1:undefined,toughness:i===4?1:undefined,abilities:[]});
const db=applyTargetedDeckSpecialImplementations(raw),deck={id:'d',name:'d',commander:'cmd',cards:[{id:'cmd',quantity:1}]};const eng=()=>new GameEngine(deck,{...deck,id:'o'},db,{validateDecks:false,rng:()=>.5});let n=0;function put(e,p,id,extra={}){let c={instanceId:`${id}-${++n}`,cardId:id,owner:p,controller:p,zone:'battlefield',tapped:false,phasedOut:false,summoningSick:false,counters:{},damageMarked:0,modifiers:{power:0,toughness:0,keywords:[]},...extra};e.state.players[p].battlefield.push(c);return c;}
test('special batch certified',()=>{for(let i=0;i<5;i++){assert.equal(db['s'+i].certificationEligible,true);assert.equal(db['s'+i].targetedImplementation,'rakdos-deck-special-v1')}});
test('Deadly Rollick costs zero while controlling commander',()=>{let e=eng(),p=e.playerIds()[0];let cmd=put(e,p,'cmd',{isCommander:true});let card={instanceId:'rollick',cardId:'s0',owner:p,controller:p,zone:'hand'};let cost=e.costs.determineSpellCost(p,card,{zone:'hand'});assert.equal(cost.finalManaCost,'');e.state.players[p].battlefield=e.state.players[p].battlefield.filter(x=>x!==cmd);cost=e.costs.determineSpellCost(p,card,{zone:'hand'});assert.equal(cost.finalManaCost,'{3}{B}')});
test('Pyroblast conditional destroy only destroys blue permanent',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],b=put(e,o,'blue'),r=put(e,o,'red');e.effects.resolve({type:'destroyTargetIfBlue'},{controller:p,source:{instanceId:'py',cardId:'s1',controller:p},targets:[r.instanceId],targeted:true});assert.ok(e.findPermanent(r.instanceId));e.effects.resolve({type:'destroyTargetIfBlue'},{controller:p,source:{instanceId:'py',cardId:'s1',controller:p},targets:[b.instanceId],targeted:true});assert.equal(e.findPermanent(b.instanceId),null)});
test('Forsaken Wastes prevents life gain and upkeep loses one',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'s2');let life=e.state.players[o].life;e.changeLife(o,5);assert.equal(e.state.players[o].life,life);e.effects.resolve({type:'activePlayerLosesLife',amount:1},{controller:p});assert.equal(e.state.players[e.state.activePlayer].life,39)});
test('Glistening Oil grants infect to attached creature and upkeep counter effect works',()=>{let e=eng(),p=e.playerIds()[0],a=put(e,p,'s3'),c=put(e,p,'red');a.attachedTo=c.instanceId;assert.ok(e.static.derivedStats(c).keywords.includes('infect'));e.effects.resolve({type:'addCounterAttached',counter:'-1/-1',amount:1},{controller:p,source:a});assert.equal(c.counters['-1/-1'],1)});
test('Thief of Blood entry flag is present for authoritative entry handling',()=>assert.equal(db.s4.asEntersRemoveAllPermanentCounters,true));
