import test from 'node:test';import assert from 'node:assert/strict';import {applyTargetedDeckPunishment3Implementations} from '../src/cards/index.js';import {GameEngine} from '../src/engine/GameEngine.js';import {EVENT} from '../src/engine/constants.js';
const names=['Syr Konrad, the Grim','Harsh Mentor','Hexing Squelcher','Persistent Constrictor','The Lord of Pain','Valgavoth, Harrower of Souls'];
const raw={cmd:{id:'cmd',name:'Commander',typeLine:'Legendary Creature',manaCost:'{B}{R}',colors:['B','R'],power:2,toughness:2,abilities:[]},bear:{id:'bear',name:'Bear',typeLine:'Creature',manaCost:'{1}{G}',colors:['G'],power:2,toughness:2,abilities:[]},rock:{id:'rock',name:'Rock',typeLine:'Artifact',manaCost:'{1}',abilities:[{type:'activated',cost:{mana:'{0}'},effect:{type:'gainLife',amount:1}}]}};names.forEach((n,i)=>raw['c'+i]={id:'c'+i,name:n,typeLine:'Legendary Creature',manaCost:'{3}{B}',colors:['B'],power:5,toughness:5,abilities:[]});const db=applyTargetedDeckPunishment3Implementations(raw),deck={id:'d',name:'d',commander:'cmd',cards:[{id:'cmd',quantity:1}]};const eng=()=>new GameEngine(deck,{...deck,id:'o'},db,{validateDecks:false,rng:()=>.5});let n=0;function put(e,p,id){let c={instanceId:`${id}-${++n}`,cardId:id,owner:p,controller:p,zone:'battlefield',tapped:false,phasedOut:false,summoningSick:false,counters:{},damageMarked:0,modifiers:{power:0,toughness:0,keywords:[]}};e.state.players[p].battlefield.push(c);return c;}function resolve(e){e.triggers.flush();let g=30;while(e.state.stack.length&&g--&&!e.state.pendingChoice)e.resolution.resolveTop();}
test('six punishment tranche cards certified',()=>{for(let i=0;i<6;i++){assert.equal(db['c'+i].certificationEligible,true);assert.equal(db['c'+i].targetedImplementation,'rakdos-deck-punishment-v3')}});
test('Valgavoth rewards only first opponent life loss in that turn',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],v=put(e,p,'c5');e.state.players[p].library.push({instanceId:'draw1',cardId:'bear',owner:p,controller:p,zone:'library'});const hand=e.state.players[p].hand.length;e.changeLife(o,-1);resolve(e);assert.equal(v.counters['+1/+1'],1);assert.equal(e.state.players[p].hand.length,hand+1);e.changeLife(o,-1);resolve(e);assert.equal(v.counters['+1/+1'],1)});
test('Syr Konrad damages each opponent for another creature dying',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'c0');let life=e.state.players[o].life;e.emit(EVENT.CREATURE_DIED,{controller:o,object:{instanceId:'dead',cardId:'bear',owner:o,controller:o,zone:'graveyard'}});resolve(e);assert.equal(e.state.players[o].life,life-1)});
test('Harsh Mentor punishes opponent nonmana artifact activation event',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'c1');let r=put(e,o,'rock'),life=e.state.players[o].life;e.emit(EVENT.ABILITY_ACTIVATED,{controller:o,source:r,object:r,ability:{type:'activated'},manaAbility:false});resolve(e);assert.equal(e.state.players[o].life,life-2)});
test('Hexing Squelcher gives itself life ward and other controlled creatures life ward',()=>{let e=eng(),p=e.playerIds()[0],h=put(e,p,'c2'),b=put(e,p,'bear');assert.equal(e.mechanics.wardCost(h).life,2);assert.equal(e.mechanics.wardCost(b).life,2)});
test('Persistent Constrictor upkeep drains opponent and can place counter',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'c3');let b=put(e,o,'bear'),life=e.state.players[o].life;e.emit(EVENT.PHASE_BEGIN,{controller:o,phase:'UPKEEP'});resolve(e);assert.equal(e.state.players[o].life,life-1);let ch=e.state.pendingChoice;assert.equal(ch?.type,'EFFECT_CARD_CHOICE');e.effects.resolveEffectCardChoice(ch,[b.instanceId]);e.state.pendingChoice=null;assert.equal(b.counters['-1/-1'],1)});
