import test from 'node:test'; import assert from 'node:assert/strict';
import { applyTargetedDeckPunishmentImplementations } from '../src/cards/index.js'; import { GameEngine } from '../src/engine/GameEngine.js'; import { EVENT } from '../src/engine/constants.js';
const raw={cmd:{id:'cmd',name:'Commander',typeLine:'Legendary Creature',manaCost:'{B}{R}',colors:['B','R'],power:2,toughness:2,abilities:[]},blood:{id:'blood',name:'Bloodchief Ascension',typeLine:'Enchantment',manaCost:'{B}',abilities:[]},exq:{id:'exq',name:'Exquisite Blood',typeLine:'Enchantment',manaCost:'{4}{B}',abilities:[]},sol:{id:'sol',name:'Solphim, Mayhem Dominus',typeLine:'Legendary Creature — Phyrexian Horror',manaCost:'{2}{R}{R}',colors:['R'],power:5,toughness:4,abilities:[]},vortex:{id:'vortex',name:'Sulfuric Vortex',typeLine:'Enchantment',manaCost:'{1}{R}{R}',abilities:[]},bolt:{id:'bolt',name:'Bolt',typeLine:'Instant',manaCost:'{R}',abilities:[]},bear:{id:'bear',name:'Bear',typeLine:'Creature',manaCost:'{1}{G}',power:2,toughness:2,abilities:[]}};
const db=applyTargetedDeckPunishmentImplementations(raw),deck={id:'d',name:'d',commander:'cmd',cards:[{id:'cmd',quantity:1}]};function eng(){return new GameEngine(deck,{...deck,id:'o'},db,{validateDecks:false,rng:()=>.5});}let n=0;function put(e,p,id,counters={}){let c={instanceId:`${id}-${++n}`,cardId:id,owner:p,controller:p,zone:'battlefield',tapped:false,phasedOut:false,summoningSick:false,counters:{...counters},damageMarked:0,modifiers:{power:0,toughness:0,keywords:[]}};e.state.players[p].battlefield.push(c);return c;}
function resolveAll(e){let guard=20;while(e.state.stack.length&&guard--){e.state.priorityPlayer=e.state.activePlayer;e.state.passes=e.playerIds().length;e.resolution.resolveTop();}}
test('punishment cards certified',()=>{for(const id of ['blood','exq','sol','vortex'])assert.equal(db[id].certificationEligible,true)});
test('Exquisite Blood gains life equal to opponent life loss',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'exq');let before=e.state.players[p].life;e.changeLife(o,-4);resolveAll(e);assert.equal(e.state.players[p].life,before+4)});
test('Sulfuric Vortex prevents all life gain and damages active player at upkeep',()=>{let e=eng(),p=e.playerIds()[0];put(e,p,'vortex');let life=e.state.players[p].life;assert.equal(e.changeLife(p,3),0);e.state.activePlayer=p;e.emit(EVENT.PHASE_BEGIN,{controller:p,phase:'UPKEEP'});resolveAll(e);assert.equal(e.state.players[p].life,life-2)});
test('Solphim doubles your noncombat damage to opponent but not combat damage',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],sol=put(e,p,'sol');let life=e.state.players[o].life;e.dealDamageToPlayer(o,3,sol,{combat:false});assert.equal(e.state.players[o].life,life-6);life=e.state.players[o].life;e.dealDamageToPlayer(o,3,sol,{combat:true});assert.equal(e.state.players[o].life,life-3)});
test('Bloodchief Ascension gets quest at end step after opponent lost 2 and drains on opponent graveyard with 3 quests',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],a=put(e,p,'blood');e.changeLife(o,-2);e.emit(EVENT.END_STEP,{controller:p});resolveAll(e);assert.equal(a.counters.quest,1);a.counters.quest=3;let lp=e.state.players[p].life,lo=e.state.players[o].life;let card={instanceId:'dead',cardId:'bear',owner:o,controller:o,zone:'hand',counters:{}};e.state.players[o].hand.push(card);e.moveToZone(card,'graveyard',o);resolveAll(e);assert.equal(e.state.players[o].life,lo-2);assert.equal(e.state.players[p].life,lp+2)});
