import test from 'node:test';
import assert from 'node:assert/strict';
import { applyTargetedDeckRemovalImplementations } from '../src/cards/index.js';
import { GameEngine } from '../src/engine/GameEngine.js';
const raw={commander:{id:'commander',name:'Commander',typeLine:'Legendary Creature',manaCost:'{B}{R}',colors:['B','R'],power:2,toughness:2,abilities:[]},smash:{id:'smash',name:'Smash to Smithereens',typeLine:'Instant',manaCost:'{1}{R}',colors:['R']},hideous:{id:'hideous',name:'Hideous End',typeLine:'Instant',manaCost:'{1}{B}{B}',colors:['B']},verdict:{id:'verdict',name:"Geth's Verdict",typeLine:'Instant',manaCost:'{B}{B}',colors:['B']},deluge:{id:'deluge',name:'Toxic Deluge',typeLine:'Sorcery',manaCost:'{2}{B}',colors:['B']},artifact:{id:'artifact',name:'Artifact',typeLine:'Artifact',manaCost:'{1}',abilities:[]},white:{id:'white',name:'White Creature',typeLine:'Creature',manaCost:'{1}{W}',colors:['W'],power:2,toughness:2,abilities:[]},black:{id:'black',name:'Black Creature',typeLine:'Creature',manaCost:'{1}{B}',colors:['B'],power:4,toughness:4,abilities:[]}};
const db=applyTargetedDeckRemovalImplementations(raw); const deck={id:'d',name:'d',commander:'commander',cards:[{id:'commander',quantity:1}]};
function eng(){return new GameEngine(deck,{...deck,id:'o',name:'o'},db,{validateDecks:false,rng:()=>0.5});}
let n=0; function put(e,pid,id){const c={instanceId:`${id}-${++n}`,cardId:id,owner:pid,controller:pid,zone:'battlefield',tapped:false,phasedOut:false,summoningSick:false,counters:{},damageMarked:0,modifiers:{power:0,toughness:0,keywords:[]}};e.state.players[pid].battlefield.push(c);return c;}
test('second removal tranche is certified',()=>{for(const id of ['smash','hideous','verdict','deluge']) assert.equal(db[id].certificationEligible,true,id);});
test('Smash destroys artifact and damages its controller 3',()=>{const e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],a=put(e,o,'artifact'),life=e.state.players[o].life;e.effects.resolve(db.smash.spellEffects[0],{controller:p,source:{cardId:'smash'},targets:[a.instanceId],targeted:true});assert.equal(e.findPermanent(a.instanceId),null);assert.equal(e.state.players[o].life,life-3);});
test('Hideous End rejects black targets and destroys nonblack creature then loses 2',()=>{const e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],w=put(e,o,'white'),b=put(e,o,'black');assert.equal(e.targeting.isLegalTarget(p,w.instanceId,db.hideous.targets,{sourceObject:{cardId:'hideous'}}),true);assert.equal(e.targeting.isLegalTarget(p,b.instanceId,db.hideous.targets,{sourceObject:{cardId:'hideous'}}),false);const life=e.state.players[o].life;e.effects.resolve(db.hideous.spellEffects[0],{controller:p,targets:[w.instanceId],targeted:true});assert.equal(e.findPermanent(w.instanceId),null);assert.equal(e.state.players[o].life,life-2);});
test("Geth's Verdict makes targeted opponent choose and sacrifice a creature, then lose 1",()=>{const e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],a=put(e,o,'white'),b=put(e,o,'black'),life=e.state.players[o].life;e.effects.resolve(db.verdict.spellEffects[0],{controller:p,targets:[o],targeted:true});assert.equal(e.state.pendingChoice?.playerId,o);e.effects.resolveEffectCardChoice(e.state.pendingChoice,[b.instanceId]);e.state.pendingChoice=null;assert.equal(e.findPermanent(b.instanceId),null);assert.ok(e.findPermanent(a.instanceId));assert.equal(e.state.players[o].life,life-1);});
test('Toxic Deluge X mode pays X life and gives every creature -X/-X',()=>{const e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],a=put(e,p,'black'),b=put(e,o,'white');const mode=e._modeFor(db.deluge,'toxic-x-3');assert.equal(mode.xValue,3);const info=e._castCostInfo(p,{instanceId:'d1',cardId:'deluge',zone:'hand'},'hand','toxic-x-3',[]);assert.deepEqual(info.lockedCost.nonManaCosts,[{type:'payLife',amount:3}]);e.effects.resolve(mode.effects[0],{controller:p,xValue:3});assert.equal(e.static.derivedStats(a).power,1);assert.equal(e.findPermanent(b.instanceId),null);});
