import test from 'node:test';import assert from 'node:assert/strict';import {applyTargetedDeckPunishment2Implementations} from '../src/cards/index.js';import {GameEngine} from '../src/engine/GameEngine.js';import {EVENT} from '../src/engine/constants.js';
const names=['Roiling Vortex','Underworld Dreams','Mogis, God of Slaughter','Razorkin Needlehead','Blood Seeker','Kederekt Parasite','Zo-Zu the Punisher','Scrawling Crawler'];
const raw={cmd:{id:'cmd',name:'Commander',typeLine:'Legendary Creature',manaCost:'{B}{R}',colors:['B','R'],power:2,toughness:2,abilities:[]},bear:{id:'bear',name:'Bear',typeLine:'Creature',manaCost:'{1}{G}',colors:['G'],power:2,toughness:2,abilities:[]},red:{id:'red',name:'Red Permanent',typeLine:'Enchantment',manaCost:'{R}',colors:['R'],abilities:[]},land:{id:'land',name:'Land',typeLine:'Land',manaCost:'',abilities:[]}};names.forEach((n,i)=>raw['c'+i]={id:'c'+i,name:n,typeLine:n==='Underworld Dreams'||n==='Roiling Vortex'?'Enchantment':'Creature',manaCost:i===5?'{B}':'{1}{R}',colors:i===5?['B']:['R'],power:2,toughness:2,abilities:[]});
const db=applyTargetedDeckPunishment2Implementations(raw),deck={id:'d',name:'d',commander:'cmd',cards:[{id:'cmd',quantity:1}]};const eng=()=>new GameEngine(deck,{...deck,id:'o'},db,{validateDecks:false,rng:()=>.5});let n=0;function put(e,p,id){let c={instanceId:`${id}-${++n}`,cardId:id,owner:p,controller:p,zone:'battlefield',tapped:false,phasedOut:false,summoningSick:false,counters:{},damageMarked:0,modifiers:{power:0,toughness:0,keywords:[]}};e.state.players[p].battlefield.push(c);return c;}function resolve(e){e.triggers.flush();let g=30;while(e.state.stack.length&&g--&&!e.state.pendingChoice)e.resolution.resolveTop();}
test('eight punishment cards certified',()=>{for(let i=0;i<8;i++)assert.equal(db['c'+i].certificationEligible,true)});
test('draw punishers work',()=>{for(const id of ['c1','c3']){let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,id);let life=e.state.players[o].life;e.emit(EVENT.CARD_DRAWN,{controller:o,card:{}});resolve(e);assert.equal(e.state.players[o].life,life-1)}});
test('Zo-Zu damages land controller',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'c6');let life=e.state.players[o].life;e.emit(EVENT.LAND_PLAYED,{controller:o,target:{}});resolve(e);assert.equal(e.state.players[o].life,life-2)});
test('Blood Seeker optional trigger can drain entering opponent creature',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'c4');let life=e.state.players[o].life;e.emit(EVENT.ENTER_BATTLEFIELD,{controller:o,target:{instanceId:'x',cardId:'bear',controller:o,owner:o,zone:'battlefield'}});e.triggers.flush();assert.equal(e.state.pendingChoice?.type,'OPTIONAL_TRIGGER');e.triggers.chooseOptional(e.state.pendingChoice.triggerId,true);resolve(e);assert.equal(e.state.players[o].life,life-1)});
test('Kederekt requires red permanent and is optional',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'c5');e.emit(EVENT.CARD_DRAWN,{controller:o,card:{}});e.triggers.flush();assert.notEqual(e.state.pendingChoice?.type,'OPTIONAL_TRIGGER');put(e,p,'red');e.emit(EVENT.CARD_DRAWN,{controller:o,card:{}});e.triggers.flush();assert.equal(e.state.pendingChoice?.type,'OPTIONAL_TRIGGER')});
test('Mogis opponent may decline sacrifice and take two',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'c2');put(e,o,'bear');let life=e.state.players[o].life;e.emit(EVENT.PHASE_BEGIN,{controller:o,phase:'UPKEEP'});resolve(e);assert.equal(e.state.pendingChoice?.type,'EFFECT_CARD_CHOICE');e.effects.resolveEffectCardChoice(e.state.pendingChoice,[]);e.state.pendingChoice=null;assert.equal(e.state.players[o].life,life-2)});
test('Roiling Vortex upkeep and free spell punish',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'c0');let life=e.state.players[o].life;e.state.activePlayer=o;e.emit(EVENT.PHASE_BEGIN,{controller:o,phase:'UPKEEP'});resolve(e);e.emit(EVENT.SPELL_CAST,{controller:o,card:{manaSpent:0},manaSpent:0});resolve(e);assert.equal(e.state.players[o].life,life-6)});
test('Scrawling Crawler upkeep draws each player and opponent draw loses life',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'c7');e.state.players[p].library.push({instanceId:'lp',cardId:'bear',owner:p,controller:p,zone:'library'});e.state.players[o].library.push({instanceId:'lo',cardId:'bear',owner:o,controller:o,zone:'library'});let hp=e.state.players[p].hand.length,ho=e.state.players[o].hand.length,life=e.state.players[o].life;e.emit(EVENT.PHASE_BEGIN,{controller:p,phase:'UPKEEP'});resolve(e);resolve(e);assert.equal(e.state.players[p].hand.length,hp+1);assert.equal(e.state.players[o].hand.length,ho+1);assert.equal(e.state.players[o].life,life-1)});
test('Mogis can be paid by sacrificing and devotion controls creature type',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0],m=put(e,p,'c2');let b=put(e,o,'bear');assert.equal(e.static.isType(m,'Creature'),false);let life=e.state.players[o].life;e.emit(EVENT.PHASE_BEGIN,{controller:o,phase:'UPKEEP'});resolve(e);let ch=e.state.pendingChoice;e.effects.resolveEffectCardChoice(ch,[b.instanceId]);e.state.pendingChoice=null;assert.equal(e.findPermanent(b.instanceId),null);assert.equal(e.state.players[o].life,life)});
test('Roiling Vortex activated effect stops opponents gaining life for the turn',()=>{let e=eng(),p=e.playerIds()[0],o=e.opponents(p)[0];put(e,p,'c0');e.state.turnNumber=4;e.state.opponentsCantGainLifeUntilTurn={[o]:4};let life=e.state.players[o].life;assert.equal(e.changeLife(o,3),0);assert.equal(e.state.players[o].life,life);e.state.turnNumber=5;assert.equal(e.changeLife(o,3),3)});
test('Razorkin Needlehead has first strike only during its controllers turn',()=>{let e=eng(),p=e.playerIds()[0],r=put(e,p,'c3');e.state.activePlayer=p;assert.equal(e.static.derivedStats(r).keywords.map(x=>String(x).toLowerCase()).includes('first strike'),true);let e2=eng(),p2=e2.playerIds()[0],o2=e2.opponents(p2)[0],r2=put(e2,p2,'c3');e2.state.activePlayer=o2;assert.equal(e2.static.derivedStats(r2).keywords.map(x=>String(x).toLowerCase()).includes('first strike'),false)});
