export const PHASES = [
  'UNTAP','UPKEEP','DRAW','PRECOMBAT_MAIN','BEGIN_COMBAT','DECLARE_ATTACKERS',
  'DECLARE_BLOCKERS','FIRST_STRIKE_DAMAGE','COMBAT_DAMAGE','END_COMBAT',
  'POSTCOMBAT_MAIN','END_STEP','CLEANUP'
];
export const COLORS=['W','U','B','R','G','C'];
export const ZONES=['library','hand','battlefield','graveyard','exile','command','stack'];
export const KEYWORDS=['flying','reach','vigilance','trample','lifelink','deathtouch','haste','first strike','double strike','menace','hexproof','ward','indestructible','islandwalk','flash'];
export const EVENT={
  GAME_START:'GAME_START', TURN_START:'TURN_START', PHASE_BEGIN:'PHASE_BEGIN', LAND_PLAYED:'LAND_PLAYED',
  SPELL_CAST:'SPELL_CAST', SPELL_RESOLVED:'SPELL_RESOLVED', ENTER_BATTLEFIELD:'ENTER_BATTLEFIELD',
  LEAVE_BATTLEFIELD:'LEAVE_BATTLEFIELD', CREATURE_DIED:'CREATURE_DIED', BEGIN_COMBAT:'BEGIN_COMBAT',
  DECLARE_ATTACKERS:'DECLARE_ATTACKERS', CREATURE_ATTACKED:'CREATURE_ATTACKED', DECLARE_BLOCKERS:'DECLARE_BLOCKERS',
  COMBAT_DAMAGE:'COMBAT_DAMAGE', COMBAT_DAMAGE_PLAYER:'COMBAT_DAMAGE_PLAYER',
  LIFE_GAIN:'LIFE_GAIN', LIFE_LOSS:'LIFE_LOSS', COUNTERS_ADDED:'COUNTERS_ADDED', TOKEN_CREATED:'TOKEN_CREATED',
  CARD_DRAWN:'CARD_DRAWN', CARD_DISCARDED:'CARD_DISCARDED', SACRIFICED:'SACRIFICED', END_STEP:'END_STEP',
  BECAME_TAPPED:'BECAME_TAPPED', EXPLORED:'EXPLORED', MANA_SPENT_TO_CAST:'MANA_SPENT_TO_CAST',
  CONTROL_CHANGED:'CONTROL_CHANGED', SAGA_FINAL_RESOLVED:'SAGA_FINAL_RESOLVED'
};
