import React from 'react';
import { paymentPresentation } from '../ui/RulesUiModel.js';

function nonManaLabel(cost = {}) {
  if (cost.type === 'tap') return 'Tap the required permanent';
  if (cost.type === 'untap') return 'Untap the required permanent';
  if (cost.type === 'sacrifice') return 'Sacrifice the required permanent';
  if (cost.type === 'discard') return 'Discard the required card';
  if (cost.type === 'payLife') return `Pay ${Number(cost.amount || 0)} life`;
  if (cost.type === 'exile') return 'Exile the required card';
  if (cost.type === 'removeCounter') return `Remove ${Number(cost.amount || 1)} ${cost.counter || cost.counterType || ''} counter${Number(cost.amount || 1) === 1 ? '' : 's'}`;
  if (cost.type === 'reveal') return 'Reveal the required card';
  if (cost.type === 'return') return 'Return the required permanent';
  return cost.type || 'Additional cost';
}

/**
 * Step 39 payment preview. The component never chooses legality or mutates mana;
 * it renders the authoritative plan calculated by GameEngine and asks the player
 * to confirm that plan before the normal engine action is submitted.
 */
export default function PaymentDialog({ plan, state, db, label = 'Pay costs', onConfirm, onCancel }) {
  if (!plan) return null;
  const presentation = paymentPresentation(plan, state, db);
  return <div className="rules-modal-backdrop" role="presentation">
    <section className="rules-modal payment-dialog" role="dialog" aria-modal="true" aria-label="Mana payment">
      <header><div><span>PAYMENT PLAN</span><h2>{label}</h2><p>This plan was generated by the authoritative cost/payment engine.</p></div><div className="payment-total">{presentation.finalManaCost || 'No mana'}</div></header>
      <div className="payment-body">
        {presentation.sources.length > 0 && <div className="payment-section"><b>Mana sources</b><ul>{presentation.sources.map(source => <li key={source.id}>{source.label}{source.requiresTap ? ' · tap' : ''}</li>)}</ul></div>}
        {presentation.lifePayment > 0 && <div className="payment-section"><b>Life payment</b><span>{presentation.lifePayment}</span></div>}
        {presentation.nonManaCosts.length > 0 && <div className="payment-section"><b>Additional costs</b><ul>{presentation.nonManaCosts.map((cost, index) => <li key={`${cost.type}-${index}`}>{nonManaLabel(cost)}</li>)}</ul></div>}
        {presentation.sources.length === 0 && presentation.lifePayment === 0 && presentation.nonManaCosts.length === 0 && <p className="payment-note">The cost can be paid entirely from mana already in your pool or has no payable cost.</p>}
      </div>
      <footer><button type="button" onClick={onCancel}>Cancel</button><button type="button" className="primary" onClick={() => onConfirm?.(plan)}>Confirm payment</button></footer>
    </section>
  </div>;
}
